// Home-relief shader constants, lifted verbatim from the real site config:
// relief.fluidEffect / relief.chromaticMask / relief.scrollExtrude
#define EFFECT_AMPLITUDE 0.15
#define EFFECT_SHADOW_STRENGTH 0.3
#define EFFECT_FLUID_MAGNITUDE 0.15
#define EFFECT_FLUID_RED_COEF 2.0
#define EFFECT_FLUID_GREEN_COEF 1.0
#define EFFECT_FLUID_BLUE_COEF 1.5
#define EFFECT_LINES_SPEED 2.0
#define EFFECT_LINES_SCALE 4.0
#define EFFECT_LINES_STRENGTH 0.0
#define EFFECT_LINES_WAVE_LENGTH 0.15
#define EFFECT_BASE_COLOR vec3(122.0 / 255.0, 191.0 / 255.0, 197.0 / 255.0)
#define EFFECT_BASE_THRESHOLD 1.0
#define EFFECT_HUE_SHIFT -0.52
#define EFFECT_COLOR_RANGE 2.0

#define SCROLL_EXTRUDE_SPEED 2.0
#define SCROLL_EXTRUDE_NOISE_SIZE 7.77
#define SCROLL_EXTRUDE_MASK -1.0, 1.0
#define SCROLL_EXTRUDE_STRENGTH 1.02

#define CHROMATIC_FRESNEL_SHARPNESS 35.0
#define CHROMATIC_FRESNEL_OPACITY 0.98
#define CHROMATIC_SHADOW_RANGE vec2(0.2, 0.42)
#define CHROMATIC_SHADOW_OPACITY 0.12
